/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const createticketfromc4c_Logic = require('./code/createticketfromc4c-logic');
const largeorder_Logic_Before_Get = require('./code/largeorder-logic-before-get');
const largeorder_Logic_Before_Update = require('./code/largeorder-logic-before-update');
const openticketfromc4c_Logic = require('./code/openticketfromc4c-logic');
const largeorder_Logic_After_Create = require('./code/largeorder-logic-after-create');

class AdminService extends LCAPApplicationService {
    async init() {

        this.on('createTicketFromC4C', async (request, next) => {
            return createticketfromc4c_Logic(request);
        });

        this.before('READ', 'LargeOrder', async (request) => {
            await largeorder_Logic_Before_Get(request);
        });

        this.before('UPDATE', 'LargeOrder', async (request) => {
            await largeorder_Logic_Before_Update(request);
        });

        this.before('openTicketFromC4C', async (request) => {
            await openticketfromc4c_Logic(request);
        });

        this.after('CREATE', 'LargeOrder', async (results, request) => {
            await largeorder_Logic_After_Create(results, request);
        });

        return super.init();
    }
}


module.exports = {
    AdminService
};